title: Delightful Data Science
author: Banias Baabe
only_build_toc_files: true
execute:
  execute_notebooks: off

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/baniasbaabe/delightful-data-science
  path_to_book: .
  branch: master

html:
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: false

sphinx:
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

parse:
  myst_enable_extensions:
    - html_image
